

language: java
sudo: true
script: 
- cd cordova
- npm -version
- npm install -g n
- n stable
- echo node.js version after upgrade
- npm -version
- npm install -g \
   cordova
# - npm install -g ios-deploy

- cordova create push-test-proj com.ds.appid app-name
- cd push-test-proj
- cordova platform add android
- cordova plugin add aerogear-cordova-push


# mvn clean install;

