

language: java
sudo: false
script: 
- cd cordova
- npm -version
- sudo npm install -g n
- echo node.js version after upgrade
- npm -version
- npm install -g \
   cordova
# - npm install -g ios-deploy
- sudo cordova platform add android
- cordova plugin add aerogear-cordova-push


# mvn clean install;

