

language: java
sudo: false
script: 
- cd cordova
- npm -version
- echo node.js version after upgrade
- npm install -g n
- npm install -g n

- npm install -g \
   cordova
# - npm install -g ios-deploy
- cordova platform add android
- cordova plugin add aerogear-cordova-push


# mvn clean install;

